### ISSUE TITLE
Skiped option filterMinChars when ajax

### ISSUE THREAD

**Issue by nnnx** [iqbalfn/bootstrap-autocomplete#16]
when set `data-filter` option `data-filter-min-chars` is ignored

**Comment by iqbalfn** [comment]
providing example or a way to reproduce will be really helpful.

**Comment by nibsirahsieu** [comment]
i was hitted by this issue as well.

**Comment by kiboke** [comment]
@iqbalfn just search for it in the [code](https://github.com/iqbalfn/bootstrap-autocomplete/blob/master/src/js/autocomplete.js) - `filterMinChars` has been defined as a constant on the top, but it doesn't appear anywhere else like other options do. There should be something like `this._config.filterMinChars`, right?

**Comment by iqbalfn** [comment]
Please kindly create a pull request if you guys know how to fix the bug. I'm not currently have free time for the project.

**Comment by kiboke** [comment]
This issue can be closed now after adding a [fix](https://github.com/iqbalfn/bootstrap-autocomplete/pull/18).
